/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelProdutos;
import Controller.ClienteController;
import Model.Cliente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Model.Produtos;
import Controller.ProdutosController;


/**
 *
 * @author devdouglas
 */
public class CadastroProdutos extends javax.swing.JPanel {
    private Model.Produtos produtoExistente = null;
    /**
     * Creates new form CadastroProdutos
     */
    public CadastroProdutos() {
        initComponents();
        carregarClientes();   
        configurarFiltros();
    }
    private void carregarClientes() {
        
        ClienteController clienteController = new ClienteController();
        ArrayList<Cliente> listaClientes = clienteController.listar();
        
        
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        modeloCombo.addElement("Selecione um Cliente...");
        
        
        for (Cliente cliente : listaClientes) {
            modeloCombo.addElement(cliente.getNomeEmpresa());
        }
        
        
        cbSelecionaCliente.setModel(modeloCombo);
    }

    private void configurarFiltros() {
        
        cbTipoUnidadeProduto.setModel(new DefaultComboBoxModel<>(new String[] { 
            "UN", "KG", "CX", "LT", "PCT" 
        }));
        
        
        cbCategoriaProduto.setModel(new DefaultComboBoxModel<>(new String[] { 
            "Selecione uma Categoria...", "Alimentos", "Eletrônicos", "Limpeza", "Químicos", "Geral" 
        }));
    }
    
    public CadastroProdutos(Model.Produtos produto) {
        initComponents();
        carregarClientes();   // Carrega os clientes no combo
        configurarFiltros();  // Carrega as unidades e categorias
        this.produtoExistente = produto;
        
        // Preenche os campos com os dados do produto selecionado
        cbSelecionaCliente.setSelectedItem(produto.getCliente());
        txtNomeProduto.setText(produto.getNomeProduto());
        txtQuantidadeProdutoEstoque.setText(String.valueOf(produto.getQuantidade()));
        cbTipoUnidadeProduto.setSelectedItem(produto.getUnidade());
        cbCategoriaProduto.setSelectedItem(produto.getCategoria());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSelecionaCliente = new javax.swing.JComboBox<>();
        txtNomeProduto = new javax.swing.JTextField();
        txtQuantidadeProdutoEstoque = new javax.swing.JTextField();
        cbTipoUnidadeProduto = new javax.swing.JComboBox<>();
        btnAtribuirProduto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbCategoriaProduto = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("GERENCIAMENTO DE PRODUTOS");

        jLabel1.setText("SELECIONE O CLIENTE:");

        jLabel3.setText("NOME DO PRODUTO:");

        jLabel4.setText("QUANTIDADE:");

        jLabel5.setText("UNIDADE:");

        jLabel6.setText("CATEGORIA:");

        cbSelecionaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnAtribuirProduto.setBackground(new java.awt.Color(0, 0, 0));
        btnAtribuirProduto.setForeground(new java.awt.Color(255, 255, 255));
        btnAtribuirProduto.setText("ATRIBUIR PRODUTO");
        btnAtribuirProduto.addActionListener(this::btnAtribuirProdutoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        cbCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtribuirProduto)
                        .addGap(122, 122, 122)
                        .addComponent(btnCancelar))
                    .addComponent(jLabel6)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantidadeProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipoUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbSelecionaCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, 200, Short.MAX_VALUE)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(cbCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cbSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidadeProdutoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTipoUnidadeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cbCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtribuirProduto)
                    .addComponent(btnCancelar))
                .addContainerGap(164, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtribuirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtribuirProdutoActionPerformed
        // TODO add your handling code here:
        
        if (cbSelecionaCliente.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente válido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cbCategoriaProduto.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma categoria válida!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

      
        if (txtNomeProduto.getText().trim().isEmpty() || txtQuantidadeProdutoEstoque.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Os campos NOME DO PRODUTO e QUANTIDADE são obrigatórios!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        int quantidadeConvertida = 0;
        try {
            quantidadeConvertida = Integer.parseInt(txtQuantidadeProdutoEstoque.getText().trim());
            if (quantidadeConvertida < 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "A quantidade não pode ser um número negativo!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira apenas números inteiros no campo QUANTIDADE!", "Erro de Digitação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; 
        }

        
        Model.Produtos produtoObj;
        if (this.produtoExistente == null) {
            produtoObj = new Model.Produtos(); 
        } else {
            produtoObj = this.produtoExistente; 
        }

        
        produtoObj.setCliente(cbSelecionaCliente.getSelectedItem().toString());
        produtoObj.setNomeProduto(txtNomeProduto.getText().trim());
        produtoObj.setQuantidade(quantidadeConvertida);
        produtoObj.setUnidade(cbTipoUnidadeProduto.getSelectedItem().toString());
        produtoObj.setCategoria(cbCategoriaProduto.getSelectedItem().toString());

       
        if (this.produtoExistente == null) {
            Controller.ProdutosController controller = new Controller.ProdutosController();
            controller.salvar(produtoObj);
        }

        
        javax.swing.JOptionPane.showMessageDialog(this, "Produto gravado com sucesso!");

        
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelProdutos.GerenciamentoProdutos());
    }//GEN-LAST:event_btnAtribuirProdutoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelProdutos.GerenciamentoProdutos());
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuirProduto;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbCategoriaProduto;
    private javax.swing.JComboBox<String> cbSelecionaCliente;
    private javax.swing.JComboBox<String> cbTipoUnidadeProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtQuantidadeProdutoEstoque;
    // End of variables declaration//GEN-END:variables
}
