/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelProdutos;
import javax.swing.table.DefaultTableModel;
import Controller.ProdutosController;
import Model.Produtos;
import java.util.ArrayList;
import Telas.Dashboard;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;

/**
 *
 * @author devdouglas
 */
public class GerenciamentoProdutos extends javax.swing.JPanel {

    /**
     * Creates new form GerenciamentoProdutos
     */
    public GerenciamentoProdutos() {
        initComponents();
        atualizarTabela();
    }
    
     public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableProdutos.getModel();
        modelo.setRowCount(0); // Limpa as linhas anteriores
        
        ProdutosController controller = new ProdutosController();
        ArrayList<Produtos> listaProdutos = controller.listar();
        
        for (Produtos produto : listaProdutos) {
            Object[] linha = new Object[]{
                produto.getId(),          // Coluna 0: ID (do Banco)
                produto.getCliente(),     // Coluna 1: Cliente
                produto.getNomeProduto(), // Coluna 2: Nome Produto
                produto.getQuantidade(),  // Coluna 3: Qtd
                produto.getUnidade(),     // Coluna 4: Unidade
                produto.getCategoria()    // Coluna 5: Categoria
            };
            modelo.addRow(linha);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPesquisaCliente = new javax.swing.JTextField();
        btnCadastrarEditarProdutos = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));
        setName(""); // NOI18N

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cliente", "Nome Produto", "Qtd", "Unidade", "Categoria"
            }
        ));
        jScrollPane1.setViewportView(tableProdutos);

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("GERENCIAMENTO DE PRODUTOS");

        jLabel6.setText("Pesquisar cliente:");

        txtPesquisaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaClienteKeyReleased(evt);
            }
        });

        btnCadastrarEditarProdutos.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarEditarProdutos.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarEditarProdutos.setText("CADASTRAR/EDITAR PRODUTOS");
        btnCadastrarEditarProdutos.addActionListener(this::btnCadastrarEditarProdutosActionPerformed);

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(375, 375, 375))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addGap(233, 233, 233))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrarEditarProdutos)
                        .addGap(115, 115, 115)
                        .addComponent(btnExcluir)
                        .addGap(160, 160, 160))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPesquisaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEditarProdutos)
                    .addComponent(btnExcluir))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaClienteKeyReleased
        // TODO add your handling code here:
        String termoBusca = txtPesquisaCliente.getText().toLowerCase().trim();
        DefaultTableModel modelo = (DefaultTableModel) tableProdutos.getModel();
        modelo.setRowCount(0);
        
        ProdutosController controller = new ProdutosController();
        ArrayList<Produtos> listaProdutos = controller.listar();
        
        for (Produtos produto : listaProdutos) {
            if (termoBusca.isEmpty() || produto.getCliente().toLowerCase().contains(termoBusca)) {
                Object[] linha = new Object[]{
                    produto.getId(),
                    produto.getCliente(),
                    produto.getNomeProduto(),
                    produto.getQuantidade(),
                    produto.getUnidade(),
                    produto.getCategoria()
                };
                modelo.addRow(linha);
            }
        }
    }//GEN-LAST:event_txtPesquisaClienteKeyReleased

    private void btnCadastrarEditarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEditarProdutosActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableProdutos.getSelectedRow();
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        
        if (linhaSelecionada == -1) {
            // Nenhuma linha selecionada: Abre o formulário limpo
            dashboard.abrirPainel(new CadastroProdutos());
        } else {
            // Obtém o ID real da Coluna 0
            int idProduto = (int) tableProdutos.getValueAt(linhaSelecionada, 0);
            
            ProdutosController controller = new ProdutosController();
            Produtos produtoSelecionado = controller.buscarPorId(idProduto);
            
            if (produtoSelecionado != null) {
                dashboard.abrirPainel(new CadastroProdutos(produtoSelecionado));
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao carregar dados do produto.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCadastrarEditarProdutosActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
         int linhaSelecionada = tableProdutos.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para excluir.");
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja remover este produto do estoque?", 
            "Confirmar Exclusão", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // Recupera o ID salvo na Coluna 0 da linha clicada
                int idProduto = (int) tableProdutos.getValueAt(linhaSelecionada, 0);
                
                ProdutosController controller = new ProdutosController();
                controller.excluir(idProduto); // Exclui no MySQL
                
                atualizarTabela(); // Atualiza os dados visíveis
                JOptionPane.showMessageDialog(this, "Produto removido com sucesso!");
                
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Não foi possível excluir o produto.\nDetalhes: " + e.getMessage(), 
                    "Erro ao Excluir", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarEditarProdutos;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtPesquisaCliente;
    // End of variables declaration//GEN-END:variables
}
