/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelEnderecos;
import Controller.ClienteController;
import Model.Cliente;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Model.Endereco;
import Controller.EnderecoController;


/**
 *
 * @author devdouglas
 */
public class CadastroEnderecos extends javax.swing.JPanel {
    private Model.Endereco enderecoExistente = null;
    /**
     * Creates new form CadastroEnderecos
     */
    public CadastroEnderecos() {
        initComponents();
        carregarClientes();
    }
     private void carregarClientes() {
        // 1. Instancia o controlador de clientes para pegar os dados da memória
        ClienteController clienteController = new ClienteController();
        ArrayList<Cliente> listaClientes = clienteController.listar();
        
        // 2. Cria um modelo novo para o ComboBox
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        
        // 3. Adiciona uma mensagem de instrução como primeira opção
        modeloCombo.addElement("Selecione um Cliente...");
        
        // 4. Percorre a lista de clientes cadastrados e adiciona o nome de cada empresa no combo
        for (Cliente cliente : listaClientes) {
            modeloCombo.addElement(cliente.getNomeEmpresa());
        }
        
        // 5. Aplica o novo modelo preenchido ao seu ComboBox da tela
        cbSelecioneCliente.setModel(modeloCombo);
    }
     public CadastroEnderecos(Model.Endereco endereco) {
        initComponents();
        carregarClientes(); // Carrega a lista de clientes primeiro
        this.enderecoExistente = endereco;
        
        // Preenche os campos com os dados existentes
        cbSelecioneCliente.setSelectedItem(endereco.getCliente());
        txtDescricao.setText(endereco.getDescricao());
        txtEndereco.setText(endereco.getEndereco());
        txtBairro.setText(endereco.getBairro());
        txtCidadeUf.setText(endereco.getCidadeUf());
        
        // Altera os textos visuais
        jLabel1.setText("EDIÇÃO DE ENDEREÇO");
        btnAtribuirEndereco.setText("ATUALIZAR ENDEREÇO");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSelecioneCliente = new javax.swing.JComboBox<>();
        txtDescricao = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtCidadeUf = new javax.swing.JTextField();
        btnAtribuirEndereco = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE ENDEREÇOS");

        jLabel2.setText("SELECIONE O CLIENTE:");

        jLabel3.setText("DESCRIÇÃO:");

        jLabel4.setText("ENDEREÇO:");

        jLabel5.setText("BAIRRO:");

        jLabel6.setText("CIDADE/UF:");

        txtBairro.addActionListener(this::txtBairroActionPerformed);

        btnAtribuirEndereco.setBackground(new java.awt.Color(0, 0, 0));
        btnAtribuirEndereco.setForeground(new java.awt.Color(255, 255, 255));
        btnAtribuirEndereco.setText("ATRIBUIR ENDEREÇO");
        btnAtribuirEndereco.addActionListener(this::btnAtribuirEnderecoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        jButton3.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAtribuirEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(btnCancelar))
                    .addComponent(cbSelecioneCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescricao)
                    .addComponent(txtEndereco)
                    .addComponent(txtBairro)
                    .addComponent(txtCidadeUf)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jButton3))
                .addContainerGap(240, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSelecioneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(22, 22, 22)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(txtCidadeUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtribuirEndereco)
                    .addComponent(btnCancelar))
                .addGap(130, 130, 130)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btnAtribuirEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtribuirEnderecoActionPerformed
        // TODO add your handling code here:
        
        int indiceSelecionado = cbSelecioneCliente.getSelectedIndex();
        if (indiceSelecionado <= 0) { // 0 é o texto "Selecione um Cliente..."
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente válido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        if (txtDescricao.getText().trim().isEmpty() || txtEndereco.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Os campos DESCRIÇÃO e ENDEREÇO são obrigatórios!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        Model.Endereco enderecoObj;
        if (this.enderecoExistente == null) {
            enderecoObj = new Model.Endereco(); // Novo Endereço
        } else {
            enderecoObj = this.enderecoExistente; // Edita o existente
        }

        
        enderecoObj.setCliente(cbSelecioneCliente.getSelectedItem().toString());
        enderecoObj.setDescricao(txtDescricao.getText().trim());
        enderecoObj.setEndereco(txtEndereco.getText().trim());
        enderecoObj.setBairro(txtBairro.getText().trim());
        enderecoObj.setCidadeUf(txtCidadeUf.getText().trim());

        
        if (this.enderecoExistente == null) {
            Controller.EnderecoController controller = new Controller.EnderecoController();
            controller.salvar(enderecoObj);
        }

        
        javax.swing.JOptionPane.showMessageDialog(this, "Endereço gravado com sucesso!");

        
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelEnderecos.GerenciamentoEnderecos());
    }//GEN-LAST:event_btnAtribuirEnderecoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelEnderecos.GerenciamentoEnderecos());
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtribuirEndereco;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbSelecioneCliente;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCidadeUf;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtEndereco;
    // End of variables declaration//GEN-END:variables
}
