/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelEnderecos;
import javax.swing.table.DefaultTableModel;
import Controller.EnderecoController;
import Model.Endereco;
import java.util.ArrayList;
import Telas.Dashboard;
import javax.swing.SwingUtilities;
import javax.swing.JOptionPane;


/**
 *
 * @author devdouglas
 */
public class GerenciamentoEnderecos extends javax.swing.JPanel {

    /**
     * Creates new form GerenciamentoEnderecos
     */
    public GerenciamentoEnderecos() {
        initComponents();
        atualizarTabela(); 
    }
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableEnderecos.getModel();
        modelo.setRowCount(0); // Limpa as linhas padrão do componente
        
        EnderecoController controller = new EnderecoController();
        ArrayList<Endereco> listaEnderecos = controller.listar();
        
        for (Endereco endereco : listaEnderecos) {
            Object[] linha = new Object[]{
                endereco.getId(),        // Coluna 0 (ID do Banco)
                endereco.getCliente(),   // Coluna 1
                endereco.getDescricao(), // Coluna 2
                endereco.getEndereco(),  // Coluna 3
                endereco.getBairro(),    // Coluna 4
                endereco.getCidadeUf()   // Coluna 5
            };
            modelo.addRow(linha);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnderecos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        PesquisarClientetxt = new javax.swing.JTextField();
        btnCadastrarEditarEndereco = new javax.swing.JButton();
        ExcluirEndereçobtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE ENDEREÇOS");

        tableEnderecos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Descrição", "Endereço", "Bairro", "Cidade/UF"
            }
        ));
        jScrollPane1.setViewportView(tableEnderecos);

        jLabel2.setText("Pesquisar cliente:");

        PesquisarClientetxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisarClientetxtKeyReleased(evt);
            }
        });

        btnCadastrarEditarEndereco.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarEditarEndereco.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarEditarEndereco.setText("CADASTRAR/EDITAR ENDEREÇO");
        btnCadastrarEditarEndereco.addActionListener(this::btnCadastrarEditarEnderecoActionPerformed);

        ExcluirEndereçobtn.setBackground(new java.awt.Color(255, 0, 0));
        ExcluirEndereçobtn.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirEndereçobtn.setText("EXCLUIR");
        ExcluirEndereçobtn.addActionListener(this::ExcluirEndereçobtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PesquisarClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(btnCadastrarEditarEndereco)
                        .addGap(115, 115, 115)
                        .addComponent(ExcluirEndereçobtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(PesquisarClientetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEditarEndereco)
                    .addComponent(ExcluirEndereçobtn))
                .addContainerGap(218, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEditarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEditarEnderecoActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableEnderecos.getSelectedRow();
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        
        if (linhaSelecionada == -1) {
            // Nenhuma linha selecionada: Abre formulário em branco
            dashboard.abrirPainel(new CadastroEnderecos());
        } else {
            // Pega o ID que está guardado na Coluna 0 da tabela
            int idEndereco = (int) tableEnderecos.getValueAt(linhaSelecionada, 0);
            
            EnderecoController controller = new EnderecoController();
            Endereco enderecoSelecionado = controller.buscarPorId(idEndereco);
            
            if (enderecoSelecionado != null) {
                dashboard.abrirPainel(new CadastroEnderecos(enderecoSelecionado));
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao buscar detalhes do endereço.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    
    }//GEN-LAST:event_btnCadastrarEditarEnderecoActionPerformed

    private void ExcluirEndereçobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirEndereçobtnActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableEnderecos.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um endereço na tabela para excluir.");
            return;
        }
        
        int confirmacao = JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja remover este endereço?", 
            "Confirmar Exclusão", 
            JOptionPane.YES_NO_OPTION
        );
        
        if (confirmacao == JOptionPane.YES_OPTION) {
            try {
                // Obtém o ID real do banco na coluna 0
                int idEndereco = (int) tableEnderecos.getValueAt(linhaSelecionada, 0);
                
                EnderecoController controller = new EnderecoController();
                controller.excluir(idEndereco); // Chama o banco via DAO
                
                atualizarTabela(); // Recarrega do BD
                JOptionPane.showMessageDialog(this, "Endereço excluído com sucesso!");
                
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(
                    this, 
                    "Não foi possível excluir o endereço.\nDetalhes: " + e.getMessage(), 
                    "Erro ao Excluir", 
                    JOptionPane.ERROR_MESSAGE
                );
            }
        }
    
    }//GEN-LAST:event_ExcluirEndereçobtnActionPerformed

    private void PesquisarClientetxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisarClientetxtKeyReleased
        // TODO add your handling code here:
       String termoBusca = PesquisarClientetxt.getText().toLowerCase().trim();
        DefaultTableModel modelo = (DefaultTableModel) tableEnderecos.getModel();
        modelo.setRowCount(0);
        
        EnderecoController controller = new EnderecoController();
        ArrayList<Endereco> listaEnderecos = controller.listar();
        
        for (Endereco endereco : listaEnderecos) {
            if (termoBusca.isEmpty() || endereco.getCliente().toLowerCase().contains(termoBusca)) {
                Object[] linha = new Object[]{
                    endereco.getId(),
                    endereco.getCliente(),
                    endereco.getDescricao(),
                    endereco.getEndereco(),
                    endereco.getBairro(),
                    endereco.getCidadeUf()
                };
                modelo.addRow(linha);
            }
        }
    }//GEN-LAST:event_PesquisarClientetxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExcluirEndereçobtn;
    private javax.swing.JTextField PesquisarClientetxt;
    private javax.swing.JButton btnCadastrarEditarEndereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEnderecos;
    // End of variables declaration//GEN-END:variables
}
