/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelRotas;
import Controller.ExpedicaoController;
import Model.Expedicao;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import Model.Rotas;
import Controller.RotasController;
import Controller.EnderecoController;
import Model.Endereco;




/**
 *
 * @author devdouglas
 */
public class CadastrarRotas extends javax.swing.JPanel {
    private Model.Rotas rotaExistente = null; 
    /**
     * Ao selecionar o pedido os dados de cliente e motorista deve ser preenchido automaticamento com os dados
     * inseridos na expedição, neste painel deve ser possível selecionar apenas o endereço de entrega
     * e automaticamente deve ser criado com status pendente.
     */
    public CadastrarRotas() {
        initComponents();
        
        // Bloqueia a digitação manual dos campos de texto (Regra de Negócio)
        txtCliente.setEditable(false);
        txtMotorista.setEditable(false);
        
        // Define o status inicial padrão fixo visualmente
        cbStatusEntrega.setModel(new DefaultComboBoxModel<>(new String[] { "Pendente" }));
        cbStatusEntrega.setEnabled(false); // Fica travado como Pendente ao cadastrar
        
        carregarPedidosExpedidos();
    }
    
    private void carregarPedidosExpedidos() {
        ExpedicaoController expedicaoController = new ExpedicaoController();
        ArrayList<Expedicao> listaPedidos = expedicaoController.listar();
        
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        modeloCombo.addElement("Selecione um Pedido...");
        
        int numeroPedido = 1;
        for (Expedicao exp : listaPedidos) {
            // Mostra o número sequencial e o cliente do pedido para facilitar a escolha
            modeloCombo.addElement("Pedido #" + numeroPedido + " - " + exp.getCliente());
            numeroPedido++;
        }
        
        cbSelecionaPedido.setModel(modeloCombo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbSelecionaPedido = new javax.swing.JComboBox<>();
        txtCliente = new javax.swing.JTextField();
        txtMotorista = new javax.swing.JTextField();
        cbSelecionaEndereco = new javax.swing.JComboBox<>();
        cbStatusEntrega = new javax.swing.JComboBox<>();
        SalvarRotabtn = new javax.swing.JButton();
        Cancelarbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("GERENCIAMENTO DE ROTAS");

        jLabel1.setText("SELECIONE O PEDIDO:");

        jLabel3.setText("CLIENTE:");

        jLabel4.setText("MOTORISTA:");

        jLabel5.setText("SELECIONE O ENDEREÇO DE ENTREGA:");

        jLabel6.setText("STATUS:");

        cbSelecionaPedido.addActionListener(this::cbSelecionaPedidoActionPerformed);

        txtCliente.addActionListener(this::txtClienteActionPerformed);

        txtMotorista.addActionListener(this::txtMotoristaActionPerformed);

        cbSelecionaEndereco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbSelecionaEndereco.addActionListener(this::cbSelecionaEnderecoActionPerformed);

        cbStatusEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cbStatusEntrega.addActionListener(this::cbStatusEntregaActionPerformed);

        SalvarRotabtn.setBackground(new java.awt.Color(0, 0, 0));
        SalvarRotabtn.setForeground(new java.awt.Color(255, 255, 255));
        SalvarRotabtn.setText("SALVAR");
        SalvarRotabtn.addActionListener(this::SalvarRotabtnActionPerformed);

        Cancelarbtn.setBackground(new java.awt.Color(0, 0, 0));
        Cancelarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelarbtn.setText("CANCELAR");
        Cancelarbtn.addActionListener(this::CancelarbtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtMotorista, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCliente, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbSelecionaPedido, javax.swing.GroupLayout.Alignment.LEADING, 0, 201, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbStatusEntrega, javax.swing.GroupLayout.Alignment.LEADING, 0, 201, Short.MAX_VALUE)
                        .addComponent(cbSelecionaEndereco, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SalvarRotabtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Cancelarbtn))
                        .addComponent(jLabel5)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbSelecionaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(cbSelecionaEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbStatusEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalvarRotabtn)
                    .addComponent(Cancelarbtn))
                .addContainerGap(159, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarRotabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarRotabtnActionPerformed
        // TODO add your handling code here:
        
        if (cbSelecionaPedido.getSelectedIndex() <= 0 && this.rotaExistente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um pedido válido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (cbSelecionaEndereco.getSelectedIndex() <= 0 && this.rotaExistente == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um endereço de entrega válido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        Model.Rotas rotaObj;
        if (this.rotaExistente == null) {
            rotaObj = new Model.Rotas(); // Nova Rota
            
            
            String textoCombo = cbSelecionaPedido.getSelectedItem().toString();
            String pedidoDisplay = textoCombo.split(" - ")[0]; 
            
            rotaObj.setPedidoDisplay(pedidoDisplay);
            rotaObj.setCliente(txtCliente.getText());
            rotaObj.setMotorista(txtMotorista.getText());
            rotaObj.setEnderecoEntrega(cbSelecionaEndereco.getSelectedItem().toString());
            rotaObj.setStatus("Pendente"); // Regra de negócio: nascer automático como Pendente
        } else {
            rotaObj = this.rotaExistente; // Edita a rota existente
            rotaObj.setStatus(cbStatusEntrega.getSelectedItem().toString()); // Atualiza o status escolhido
        }

        
        if (this.rotaExistente == null) {
            Controller.RotasController controller = new Controller.RotasController();
            controller.salvar(rotaObj);
        }

        
        javax.swing.JOptionPane.showMessageDialog(this, "Rota gravada com sucesso!");

        
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelRotas.GerenciamentoRotas());
    }//GEN-LAST:event_SalvarRotabtnActionPerformed

    private void CancelarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarbtnActionPerformed
        // TODO add your handling code here:
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelRotas.GerenciamentoRotas());
    }//GEN-LAST:event_CancelarbtnActionPerformed

    private void cbStatusEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusEntregaActionPerformed

    private void cbSelecionaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelecionaEnderecoActionPerformed
        // TODO add your handling code here:
        int indiceSelecionado = cbSelecionaPedido.getSelectedIndex();
        
        // Se selecionou a opção em branco ou instrução, limpa tudo
        if (indiceSelecionado <= 0) {
            txtCliente.setText("");
            txtMotorista.setText("");
            cbSelecionaEndereco.setModel(new DefaultComboBoxModel<>(new String[] { " " }));
            return;
        }
        
        int indiceRealNoDAO = indiceSelecionado - 1;
        
        ExpedicaoController expedicaoController = new ExpedicaoController();
        Expedicao pedidoSelecionado = expedicaoController.listar().get(indiceRealNoDAO);
        
        // 1. Preenche os campos de texto automáticos
        String nomeCliente = pedidoSelecionado.getCliente();
        txtCliente.setText(nomeCliente);
        txtMotorista.setText(pedidoSelecionado.getMotorista());
        
        // 2. FILTRAGEM DINÂMICA DE ENDEREÇOS DO CLIENTE
        EnderecoController enderecoController = new EnderecoController();
        ArrayList<Endereco> todosEnderecos = enderecoController.listar();
        
        DefaultComboBoxModel<String> modeloEndereco = new DefaultComboBoxModel<>();
        modeloEndereco.addElement("Selecione o Endereço de Entrega...");
        
        // Percorre todos os endereços e adiciona apenas os que são do cliente selecionado
        for (Endereco end : todosEnderecos) {
            if (end.getCliente().equalsIgnoreCase(nomeCliente)) {
                // Mostra a descrição e o endereço físico (Ex: "Filial - Rua das Flores, 123")
                modeloEndereco.addElement(end.getDescricao() + " - " + end.getEndereco());
                
                // Nota: Se na sua classe Endereco.java o campo de texto da rua se chamar "getEndereco()", mude para:
                // modeloEndereco.addElement(end.getDescricao() + " - " + end.getEndereco());
            }
        }
        
        // 3. Aplica os endereços filtrados no ComboBox da tela
        cbSelecionaEndereco.setModel(modeloEndereco);
    }//GEN-LAST:event_cbSelecionaEnderecoActionPerformed

    private void txtMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotoristaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotoristaActionPerformed

    private void txtClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClienteActionPerformed

    private void cbSelecionaPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSelecionaPedidoActionPerformed
        // TODO add your handling code here:
        int indiceSelecionado = cbSelecionaPedido.getSelectedIndex();
        
        // Se selecionou a primeira opção ("Selecione um Pedido...") ou nada, limpa os campos
        if (indiceSelecionado <= 0) {
            txtCliente.setText("");
            txtMotorista.setText("");
            cbSelecionaEndereco.setModel(new DefaultComboBoxModel<>(new String[] { " " }));
            return;
        }
        
        // Como o índice 0 é a mensagem informativa, o pedido real na lista do DAO está na posição (indice - 1)
        int indiceRealNoDAO = indiceSelecionado - 1;
        
        ExpedicaoController expedicaoController = new ExpedicaoController();
        Expedicao pedidoSelecionado = expedicaoController.listar().get(indiceRealNoDAO);
        
        // Preenche automaticamente as caixas de texto com os dados da expedição
        txtCliente.setText(pedidoSelecionado.getCliente());
        txtMotorista.setText(pedidoSelecionado.getMotorista());
    }//GEN-LAST:event_cbSelecionaPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelarbtn;
    private javax.swing.JButton SalvarRotabtn;
    private javax.swing.JComboBox<String> cbSelecionaEndereco;
    private javax.swing.JComboBox<String> cbSelecionaPedido;
    private javax.swing.JComboBox<String> cbStatusEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtMotorista;
    // End of variables declaration//GEN-END:variables
}
