/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelRotas;

import Controller.RotasController;
import Model.Rotas;
import Telas.Dashboard;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author devdouglas
 */
public class GerenciamentoRotas extends javax.swing.JPanel {

    private final RotasController controller = new RotasController();
    // Armazena as rotas que estão atualmente visíveis na tabela (respeitando o filtro)
    private ArrayList<Rotas> listaExibida = new ArrayList<>();

    public GerenciamentoRotas() {
        initComponents();
        tableRotas.setRowSelectionAllowed(true);
        cbFiltraStatus.setModel(new DefaultComboBoxModel<>(new String[]{
            "Todos", "Pendente", "Em Rota", "Entregue", "Cancelado"
        }));
        atualizarTabela();
    }

    /**
     * Carrega os dados da lista, aplica os filtros selecionados no ComboBox 
     * e renderiza o status colorido.
     */
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableRotas.getModel();
        modelo.setRowCount(0);

        String statusSelecionado = "Todos";
        if (cbFiltraStatus.getSelectedItem() != null) {
            statusSelecionado = cbFiltraStatus.getSelectedItem().toString().trim();
        }

        ArrayList<Rotas> listaCompleta = controller.listar();
        listaExibida = new ArrayList<>();

        // Configura o renderizador para pintar as cores na coluna Status (índice 4)
        tableRotas.getColumnModel().getColumn(4).setCellRenderer(new RotasStatusRenderer());

        for (Rotas rota : listaCompleta) {
            boolean deveExibir = "Todos".equalsIgnoreCase(statusSelecionado)
                    || (rota.getStatus() != null && rota.getStatus().equalsIgnoreCase(statusSelecionado));

            if (deveExibir) {
                listaExibida.add(rota); // Adiciona na lista que espelha a tabela
                Object[] linha = new Object[]{
                    rota.getPedidoDisplay(),
                    rota.getCliente(),
                    rota.getEnderecoEntrega(),
                    rota.getMotorista(),
                    rota.getStatus()
                };
                modelo.addRow(linha);
            }
        }
    }

    private void VisualizarRotabtnActionPerformed(java.awt.event.ActionEvent evt) {
        int linhaSelecionada = tableRotas.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this,
                    "Por favor, selecione uma rota na tabela para visualizar!",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Obtém o objeto Rota exatamente do índice da linha que está na tela
        Rotas rotaSelecionada = listaExibida.get(linhaSelecionada);

        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.abrirPainel(new VisualizarRota(rotaSelecionada));
        }
    }

    private void CriarEditarRotabtnActionPerformed(java.awt.event.ActionEvent evt) {
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        if (dashboard != null) {
            dashboard.abrirPainel(new CadastrarRotas());
        }
    }

    private void cbFiltraStatusItemStateChanged(java.awt.event.ItemEvent evt) {
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            atualizarTabela();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        FiltroStatusComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRotas = new javax.swing.JTable();
        VisualizarRotabtn = new javax.swing.JButton();
        CriarEditarRotabtn = new javax.swing.JButton();
        cbFiltraStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        FiltroStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Filtrar pelo status:");

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("GERENCIAMENTO DE ROTAS");

        tableRotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "Pedido", "Cliente", "Endereço", "Motorista", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableRotas);

        VisualizarRotabtn.setBackground(new java.awt.Color(0, 0, 0));
        VisualizarRotabtn.setForeground(new java.awt.Color(255, 255, 255));
        VisualizarRotabtn.setText("VISUALIZAR  ROTA");
        VisualizarRotabtn.addActionListener(this::VisualizarRotabtnActionPerformed);

        CriarEditarRotabtn.setBackground(new java.awt.Color(0, 0, 0));
        CriarEditarRotabtn.setForeground(new java.awt.Color(255, 255, 255));
        CriarEditarRotabtn.setText("CRIAR/EDITAR  ROTA");
        CriarEditarRotabtn.addActionListener(this::CriarEditarRotabtnActionPerformed);

        cbFiltraStatus.addItemListener(this::cbFiltraStatusItemStateChanged);

        jLabel4.setText("Filtrar pelo status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(VisualizarRotabtn)
                                .addGap(94, 94, 94)
                                .addComponent(CriarEditarRotabtn)
                                .addGap(43, 43, 43))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFiltraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarEditarRotabtn)
                    .addComponent(VisualizarRotabtn))
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JButton CriarEditarRotabtn;
    private javax.swing.JComboBox<String> FiltroStatusComboBox;
    private javax.swing.JButton VisualizarRotabtn;
    private javax.swing.JComboBox<String> cbFiltraStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRotas;
    // End of variables declaration                     
}