/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelRotas;
import javax.swing.table.DefaultTableModel;
import Controller.RotasController;
import Model.Rotas;
import java.util.ArrayList;
import Telas.Dashboard;
import javax.swing.SwingUtilities;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author devdouglas
 */
public class GerenciamentoRotas extends javax.swing.JPanel {

    /**
     * Status além de conter o texto deve ser identificado com cores
     * sendo azul para "Em Rota", verde para "Entregue" e vermelho para pendente.
     */
    public GerenciamentoRotas() {
        initComponents();
        tableRotas.setRowSelectionAllowed(true);
        cbFiltraStatus.setModel(new DefaultComboBoxModel<>(new String[] { "Todos", "Pendente", "Em Rota", "Entregue", "Cancelado" }));
        atualizarTabela();
    }
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableRotas.getModel();
        modelo.setRowCount(0);
        
        RotasController controller = new RotasController();
        ArrayList<Rotas> lista = controller.listar();
        
        
        tableRotas.getColumnModel().getColumn(4).setCellRenderer(new RotasStatusRenderer());
        
        for (Rotas rota : lista) {
            Object[] linha = new Object[]{
                rota.getPedidoDisplay(),
                rota.getCliente(),
                rota.getEnderecoEntrega(),
                rota.getMotorista(),
                rota.getStatus() // Será interceptado e pintado pelo Renderer
            };
            modelo.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FiltroStatusComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRotas = new javax.swing.JTable();
        VisualizarRotabtn = new javax.swing.JButton();
        CriarEditarRotabtn = new javax.swing.JButton();
        cbFiltraStatus = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();

        FiltroStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Filtrar pelo status:");

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("GERENCIAMENTO DE ROTAS");

        tableRotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cliente", "Endereço", "Motorista", "Status"
            }
        ));
        jScrollPane1.setViewportView(tableRotas);

        VisualizarRotabtn.setBackground(new java.awt.Color(0, 0, 0));
        VisualizarRotabtn.setForeground(new java.awt.Color(255, 255, 255));
        VisualizarRotabtn.setText("VISUALIZAR  ROTA");
        VisualizarRotabtn.addActionListener(this::VisualizarRotabtnActionPerformed);

        CriarEditarRotabtn.setBackground(new java.awt.Color(0, 0, 0));
        CriarEditarRotabtn.setForeground(new java.awt.Color(255, 255, 255));
        CriarEditarRotabtn.setText("CRIAR/EDITAR  ROTA");
        CriarEditarRotabtn.addActionListener(this::CriarEditarRotabtnActionPerformed);

        cbFiltraStatus.addItemListener(this::cbFiltraStatusItemStateChanged);

        jLabel4.setText("Filtrar pelo status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(VisualizarRotabtn)
                                .addGap(94, 94, 94)
                                .addComponent(CriarEditarRotabtn)
                                .addGap(43, 43, 43))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFiltraStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CriarEditarRotabtn)
                    .addComponent(VisualizarRotabtn))
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void VisualizarRotabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VisualizarRotabtnActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableRotas.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione uma rota na tabela para visualizar!");
            return;
        }
        
        Controller.RotasController controller = new Controller.RotasController();
        Model.Rotas rotaSelecionada = controller.listar().get(linhaSelecionada);
        
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new VisualizarRota(rotaSelecionada));
                                                     
    
    }//GEN-LAST:event_VisualizarRotabtnActionPerformed

    private void CriarEditarRotabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CriarEditarRotabtnActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
       
        dashboard.abrirPainel(new CadastrarRotas());
    }//GEN-LAST:event_CriarEditarRotabtnActionPerformed

    private void cbFiltraStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFiltraStatusItemStateChanged
        // TODO add your handling code here:
        
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            
            
            String statusSelecionado = cbFiltraStatus.getSelectedItem().toString().trim();
            
            
            DefaultTableModel modelo = (DefaultTableModel) tableRotas.getModel();
            modelo.setRowCount(0);
            
            
            RotasController controller = new RotasController();
            ArrayList<Rotas> lista = controller.listar();
            
            
            tableRotas.getColumnModel().getColumn(4).setCellRenderer(new RotasStatusRenderer());
            
            
            for (Rotas rota : lista) {
               
                if ("Todos".equalsIgnoreCase(statusSelecionado) || rota.getStatus().equalsIgnoreCase(statusSelecionado)) {
                    Object[] linha = new Object[]{
                        rota.getPedidoDisplay(),
                        rota.getCliente(),
                        rota.getEnderecoEntrega(),
                        rota.getMotorista(),
                        rota.getStatus()
                    };
                    modelo.addRow(linha);}
            }
        }
    }//GEN-LAST:event_cbFiltraStatusItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CriarEditarRotabtn;
    private javax.swing.JComboBox<String> FiltroStatusComboBox;
    private javax.swing.JButton VisualizarRotabtn;
    private javax.swing.JComboBox<String> cbFiltraStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRotas;
    // End of variables declaration//GEN-END:variables
}
