/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import PanelUsuarios.GerenciamentoUsuarios;
import PanelClientes.GerenciamentoClientes;
import PanelExpedicao.GerenciamentoExpedicao;
import PanelRotas.GerenciamentoRotas;
import PanelEnderecos.GerenciamentoEnderecos;
import PanelProdutos.GerenciamentoProdutos;
/**
 *
 * @author devdouglas
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    public void abrirPainel(javax.swing.JPanel painel) {

        Conteudopainel.removeAll();
        Conteudopainel.setLayout(new java.awt.BorderLayout());

        Conteudopainel.add(painel, java.awt.BorderLayout.CENTER);

        Conteudopainel.revalidate();
        Conteudopainel.repaint();
    }
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuLateralPainel = new javax.swing.JPanel();
        Produtosbtn = new javax.swing.JButton();
        Dashboardbtn = new javax.swing.JButton();
        Usuariosbtn = new javax.swing.JButton();
        Clientesbtn = new javax.swing.JButton();
        Enderecobtn = new javax.swing.JButton();
        Rotabtn = new javax.swing.JButton();
        Expedicaobtn = new javax.swing.JButton();
        Sairbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Conteudopainel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(1200, 768));

        MenuLateralPainel.setBackground(new java.awt.Color(153, 153, 153));

        Produtosbtn.setBackground(new java.awt.Color(0, 0, 0));
        Produtosbtn.setForeground(new java.awt.Color(255, 255, 255));
        Produtosbtn.setText("PRODUTOS");
        Produtosbtn.addActionListener(this::ProdutosbtnActionPerformed);

        Dashboardbtn.setBackground(new java.awt.Color(0, 0, 0));
        Dashboardbtn.setForeground(new java.awt.Color(255, 255, 255));
        Dashboardbtn.setText("DASHBOARD");

        Usuariosbtn.setBackground(new java.awt.Color(0, 0, 0));
        Usuariosbtn.setForeground(new java.awt.Color(255, 255, 255));
        Usuariosbtn.setText("USUÁRIOS");
        Usuariosbtn.addActionListener(this::UsuariosbtnActionPerformed);

        Clientesbtn.setBackground(new java.awt.Color(0, 0, 0));
        Clientesbtn.setForeground(new java.awt.Color(255, 255, 255));
        Clientesbtn.setText("CLIENTES");
        Clientesbtn.addActionListener(this::ClientesbtnActionPerformed);

        Enderecobtn.setBackground(new java.awt.Color(0, 0, 0));
        Enderecobtn.setForeground(new java.awt.Color(255, 255, 255));
        Enderecobtn.setText("ENDEREÇOS");
        Enderecobtn.addActionListener(this::EnderecobtnActionPerformed);

        Rotabtn.setBackground(new java.awt.Color(0, 0, 0));
        Rotabtn.setForeground(new java.awt.Color(255, 255, 255));
        Rotabtn.setText("ROTAS");
        Rotabtn.addActionListener(this::RotabtnActionPerformed);

        Expedicaobtn.setBackground(new java.awt.Color(0, 0, 0));
        Expedicaobtn.setForeground(new java.awt.Color(255, 255, 255));
        Expedicaobtn.setText("EXPEDIÇÃO");
        Expedicaobtn.addActionListener(this::ExpedicaobtnActionPerformed);

        Sairbtn.setBackground(new java.awt.Color(0, 0, 0));
        Sairbtn.setForeground(new java.awt.Color(255, 255, 255));
        Sairbtn.setText("SAIR");
        Sairbtn.addActionListener(this::SairbtnActionPerformed);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/LogoSGEMenu.png"))); // NOI18N

        javax.swing.GroupLayout MenuLateralPainelLayout = new javax.swing.GroupLayout(MenuLateralPainel);
        MenuLateralPainel.setLayout(MenuLateralPainelLayout);
        MenuLateralPainelLayout.setHorizontalGroup(
            MenuLateralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLateralPainelLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(MenuLateralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLateralPainelLayout.createSequentialGroup()
                        .addGroup(MenuLateralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Clientesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Expedicaobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Enderecobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Produtosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Usuariosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Sairbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rotabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLateralPainelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(92, 92, 92))))
        );
        MenuLateralPainelLayout.setVerticalGroup(
            MenuLateralPainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLateralPainelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(Dashboardbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(Usuariosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Clientesbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(Produtosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Enderecobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Rotabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Expedicaobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(Sairbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("SISTEMA DE GERENCIAMENTO DE ENTREGAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(225, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(213, 213, 213))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Conteudopainel.setBackground(new java.awt.Color(153, 153, 153));
        Conteudopainel.setMaximumSize(new java.awt.Dimension(0, 682));
        Conteudopainel.setMinimumSize(new java.awt.Dimension(0, 682));

        javax.swing.GroupLayout ConteudopainelLayout = new javax.swing.GroupLayout(Conteudopainel);
        Conteudopainel.setLayout(ConteudopainelLayout);
        ConteudopainelLayout.setHorizontalGroup(
            ConteudopainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ConteudopainelLayout.setVerticalGroup(
            ConteudopainelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuLateralPainel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Conteudopainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuLateralPainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Conteudopainel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesbtnActionPerformed
        // TODO add your handling code here:
         abrirPainel(new GerenciamentoClientes());
    }//GEN-LAST:event_ClientesbtnActionPerformed

    private void ExpedicaobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpedicaobtnActionPerformed
        // TODO add your handling code here:
        abrirPainel(new GerenciamentoExpedicao());
    }//GEN-LAST:event_ExpedicaobtnActionPerformed

    private void RotabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RotabtnActionPerformed
        // TODO add your handling code here:
        abrirPainel(new GerenciamentoRotas());
    }//GEN-LAST:event_RotabtnActionPerformed

    private void UsuariosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariosbtnActionPerformed
        // TODO add your handling code here:
        abrirPainel(new GerenciamentoUsuarios());
    }//GEN-LAST:event_UsuariosbtnActionPerformed

    private void EnderecobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnderecobtnActionPerformed
        // TODO add your handling code here:
        abrirPainel(new GerenciamentoEnderecos());
    }//GEN-LAST:event_EnderecobtnActionPerformed

    private void ProdutosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosbtnActionPerformed
        // TODO add your handling code here:
        abrirPainel(new GerenciamentoProdutos());
    }//GEN-LAST:event_ProdutosbtnActionPerformed

    private void SairbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairbtnActionPerformed
        // TODO add your handling code here:
        TelaLogin telalogin = new TelaLogin();
        telalogin.setVisible(true);
        this.dispose();
        javax.swing.JOptionPane.showMessageDialog(this, "Sessão finalizada");
    }//GEN-LAST:event_SairbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clientesbtn;
    private javax.swing.JPanel Conteudopainel;
    private javax.swing.JButton Dashboardbtn;
    private javax.swing.JButton Enderecobtn;
    private javax.swing.JButton Expedicaobtn;
    private javax.swing.JPanel MenuLateralPainel;
    private javax.swing.JButton Produtosbtn;
    private javax.swing.JButton Rotabtn;
    private javax.swing.JButton Sairbtn;
    private javax.swing.JButton Usuariosbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
