package Telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author devdouglas
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

    /**
     * Creates new form TelaLogin2
     */
    public TelaLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Usuariotxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Senhapassword = new javax.swing.JPasswordField();
        MostrarSenhacheckbox = new javax.swing.JCheckBox();
        Entrarbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento de Entregas");
        setBackground(new java.awt.Color(153, 153, 153));
        setFocusCycleRoot(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(565, 374));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/LogoSGE(1).png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel2.setText("FAÇA SEU LOGIN");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setText("USUÁRIO:");

        Usuariotxt.addActionListener(this::UsuariotxtActionPerformed);

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("SENHA:");

        Senhapassword.addActionListener(this::SenhapasswordActionPerformed);

        MostrarSenhacheckbox.setText("Mostrar senha");
        MostrarSenhacheckbox.addActionListener(this::MostrarSenhacheckboxActionPerformed);

        Entrarbtn.setBackground(new java.awt.Color(0, 0, 0));
        Entrarbtn.setForeground(new java.awt.Color(255, 255, 255));
        Entrarbtn.setText("ENTRAR");
        Entrarbtn.setMaximumSize(new java.awt.Dimension(147, 32));
        Entrarbtn.setMinimumSize(new java.awt.Dimension(147, 32));
        Entrarbtn.addActionListener(this::EntrarbtnActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(Senhapassword, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Entrarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MostrarSenhacheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)
                        .addComponent(Usuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Senhapassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarSenhacheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(Entrarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 739, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuariotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuariotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuariotxtActionPerformed

    private void EntrarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarbtnActionPerformed
        // TODO add your handling code here:
       // 1. Captura o que o usuário digitou (Substitua pelos nomes corretos dos seus JTextFields)
        // 1. Captura os dados usando os nomes reais dos componentes da sua tela
        String loginDigitado = Usuariotxt.getText().trim();
        String senhaDigitada = new String(Senhapassword.getPassword());
        
        // 2. Validação simples de campos vazios
        if (loginDigitado.isEmpty() || senhaDigitada.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 3. Consulta o banco de dados através do Controller
        Controller.UsuarioController controller = new Controller.UsuarioController();
        Model.Usuario usuarioLogado = controller.autenticar(loginDigitado, senhaDigitada);
        
        // 4. Validação das credenciais retornadas pelo MySQL
        if (usuarioLogado != null) {
            // Guarda o perfil do usuário ativo na variável estática do seu Dashboard
            Telas.Dashboard.perfilLogado = usuarioLogado.getPerfil();
            
            // Abre a tela principal do seu sistema
            Telas.Dashboard principal = new Telas.Dashboard();
            principal.setVisible(true);
            
            // Fecha esta janela de Login atual de forma segura
            this.dispose();
            
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!", "Erro de Autenticação", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
                    
    }//GEN-LAST:event_EntrarbtnActionPerformed

    private void MostrarSenhacheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarSenhacheckboxActionPerformed
        // TODO add your handling code here:
        // Lógica para alternar a visibilidade dos caracteres da senha
        if (MostrarSenhacheckbox.isSelected()) {
            Senhapassword.setEchoChar((char) 0); // Mostra o texto limpo
        } else {
            Senhapassword.setEchoChar('•'); // Oculta com bolinhas
        }

    }//GEN-LAST:event_MostrarSenhacheckboxActionPerformed

    private void SenhapasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhapasswordActionPerformed
        // TODO add your handling code here:
        Entrarbtn.doClick();
    }//GEN-LAST:event_SenhapasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Entrarbtn;
    private javax.swing.JCheckBox MostrarSenhacheckbox;
    private javax.swing.JPasswordField Senhapassword;
    private javax.swing.JTextField Usuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
