/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelClientes;
import javax.swing.table.DefaultTableModel;
import Controller.ClienteController;
import Model.Cliente;
import java.util.ArrayList;
import Telas.Dashboard;
import javax.swing.SwingUtilities;

/**
 *
 * @author devdouglas
 */
public class GerenciamentoClientes extends javax.swing.JPanel {

    /**
     * Creates new form GerenciamentoClientes
     */
    public GerenciamentoClientes() {
        initComponents();
        atualizarTabela();
    }
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) TableClientes.getModel();
        modelo.setRowCount(0); // Limpa linhas padrão para receber os dados limpos
        
        ClienteController controller = new ClienteController();
        ArrayList<Cliente> listaClientes = controller.listar();
        
        for (Cliente cliente : listaClientes) {
            Object[] linha = new Object[]{
                cliente.getNomeEmpresa(), // Coluna 1
                cliente.getCnpj(),        // Coluna 2
                cliente.getTelefone(),    // Coluna 3
                cliente.getEmail()        // Coluna 4
            };
            modelo.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPesquisarCliente = new javax.swing.JTextField();
        btnCadastrarEditarCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientes = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE CLIENTES");

        jLabel2.setText("Pesquisar cliente:");

        txtPesquisarCliente.addActionListener(this::txtPesquisarClienteActionPerformed);
        txtPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarClienteKeyReleased(evt);
            }
        });

        btnCadastrarEditarCliente.setBackground(new java.awt.Color(0, 0, 0));
        btnCadastrarEditarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnCadastrarEditarCliente.setText("CADASTRAR/EDITAR CLIENTE");
        btnCadastrarEditarCliente.addActionListener(this::btnCadastrarEditarClienteActionPerformed);

        btnExcluirCliente.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluirCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluirCliente.setText("EXCLUIR");
        btnExcluirCliente.addActionListener(this::btnExcluirClienteActionPerformed);

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "CNPJ", "Telefone", "E-mail"
            }
        ));
        TableClientes.setPreferredSize(new java.awt.Dimension(375, 80));
        jScrollPane2.setViewportView(TableClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCadastrarEditarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExcluirCliente))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarEditarCliente)
                    .addComponent(btnExcluirCliente))
                .addGap(242, 242, 242))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarEditarClienteActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = TableClientes.getSelectedRow();
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        
        if (linhaSelecionada == -1) {
            // Nenhuma linha selecionada: Abre o cadastro em branco
            dashboard.abrirPainel(new CadastroClientes());
        } else {
            // Linha selecionada: Busca o cliente na memória e abre o construtor de edição
            ClienteController controller = new ClienteController();
            Cliente clienteSelecionado = controller.listar().get(linhaSelecionada);
            
            dashboard.abrirPainel(new CadastroClientes(clienteSelecionado));
        }
    }//GEN-LAST:event_btnCadastrarEditarClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        // TODO add your handling code here:
         int linhaSelecionada = TableClientes.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente na tabela para excluir.");
            return;
        }
        
        // 2. Exibe uma janela perguntando se ele tem certeza
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir este cliente?", 
            "Confirmar Exclusão", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        // 3. Se a resposta for SIM, remove da memória ram
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            Controller.ClienteController controller = new Controller.ClienteController();
            
            // Remove o cliente da lista com base na linha que estava selecionada
            controller.listar().remove(linhaSelecionada);
            
            // 4. Recarrega a tabela na tela para atualizar os dados
            atualizarTabela();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void txtPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarClienteActionPerformed

    private void txtPesquisarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarClienteKeyReleased
        // TODO add your handling code here:
        
        String termoBusca = txtPesquisarCliente.getText().toLowerCase().trim();
        
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TableClientes.getModel();
        modelo.setRowCount(0);
        
        
        Controller.ClienteController controller = new Controller.ClienteController();
        java.util.ArrayList<Model.Cliente> listaClientes = controller.listar();
        
        
        for (Model.Cliente cliente : listaClientes) {
            
            if (termoBusca.isEmpty() || cliente.getNomeEmpresa().toLowerCase().contains(termoBusca)) {
                Object[] linha = new Object[]{
                    cliente.getNomeEmpresa(),
                    cliente.getCnpj(),
                    cliente.getTelefone(),
                    cliente.getEmail()
                };
                modelo.addRow(linha); // Adiciona apenas o cliente filtrado na tela
            }
        }
    }//GEN-LAST:event_txtPesquisarClienteKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableClientes;
    private javax.swing.JButton btnCadastrarEditarCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtPesquisarCliente;
    // End of variables declaration//GEN-END:variables
}
