/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelUsuarios;
import Telas.Dashboard;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import Controller.UsuarioController;
import Model.Usuario;
import java.util.ArrayList;


/**
 *
 * @author devdouglas
 */
public class GerenciamentoUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form GerenciamentoUsuarios
     */
    public GerenciamentoUsuarios() {
        initComponents();
        atualizarTabela();
    }
    
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tableUsuariosCadastrados.getModel();
        modelo.setRowCount(0);
        UsuarioController controller = new UsuarioController();
        ArrayList<Usuario> listaUsuarios = controller.listar();
        for (Usuario usuario : listaUsuarios) {
            Object[] linha = new Object[]{
                usuario.getNome(),  
                usuario.getCpf(),   
                usuario.getPerfil()
            };
            modelo.addRow(linha);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PesquisaUsuariotxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUsuariosCadastrados = new javax.swing.JTable();
        CadastrarEditarUsuariobtn = new javax.swing.JButton();
        ExcluirUsuariobtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE USUÁRIOS");

        jLabel2.setText("Pesquisar usuário:");

        PesquisaUsuariotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PesquisaUsuariotxtKeyReleased(evt);
            }
        });

        tableUsuariosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuário", "CPF", "Perfil"
            }
        ));
        tableUsuariosCadastrados.setPreferredSize(new java.awt.Dimension(375, 80));
        jScrollPane1.setViewportView(tableUsuariosCadastrados);

        CadastrarEditarUsuariobtn.setBackground(new java.awt.Color(0, 0, 0));
        CadastrarEditarUsuariobtn.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarEditarUsuariobtn.setText("CADASTRAR/EDITAR USUÁRIO");
        CadastrarEditarUsuariobtn.addActionListener(this::CadastrarEditarUsuariobtnActionPerformed);

        ExcluirUsuariobtn.setBackground(new java.awt.Color(255, 0, 0));
        ExcluirUsuariobtn.setForeground(new java.awt.Color(255, 255, 255));
        ExcluirUsuariobtn.setText("EXCLUIR");
        ExcluirUsuariobtn.addActionListener(this::ExcluirUsuariobtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CadastrarEditarUsuariobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(114, 114, 114)
                        .addComponent(ExcluirUsuariobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addGap(144, 144, 144))
            .addGroup(layout.createSequentialGroup()
                .addGap(273, 273, 273)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PesquisaUsuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(209, 209, 209))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PesquisaUsuariotxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExcluirUsuariobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CadastrarEditarUsuariobtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(270, 270, 270))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarEditarUsuariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarEditarUsuariobtnActionPerformed
        // TODO add your handling code here:
         int linhaSelecionada = tableUsuariosCadastrados.getSelectedRow();
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        
        if (linhaSelecionada == -1) {
            // Nenhuma linha selecionada: Abre tela de CADASTRO normal
            dashboard.abrirPainel(new CadastroUsuarios());
        } else {
            // Linha selecionada: Pega o usuário correspondente da memória
            Controller.UsuarioController controller = new Controller.UsuarioController();
            Usuario usuarioSelecionado = controller.listar().get(linhaSelecionada);
            
            // Abre a tela passando o usuário selecionado para o NOVO CONSTRUTOR (Modo EDIÇÃO)
            dashboard.abrirPainel(new CadastroUsuarios(usuarioSelecionado));
        }
    }//GEN-LAST:event_CadastrarEditarUsuariobtnActionPerformed

    private void ExcluirUsuariobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirUsuariobtnActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableUsuariosCadastrados.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um usuário na tabela para excluir.");
            return;
        }
        
        
        int confirmacao = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "Tem certeza que deseja excluir este usuário?", 
            "Confirmar Exclusão", 
            javax.swing.JOptionPane.YES_NO_OPTION
        );
        
        
        if (confirmacao == javax.swing.JOptionPane.YES_OPTION) {
            
            Controller.UsuarioController controller = new Controller.UsuarioController();
            
            
            controller.listar().remove(linhaSelecionada);
            
            
            atualizarTabela();
            
            javax.swing.JOptionPane.showMessageDialog(this, "Usuário excluído com sucesso!");
        }
    }//GEN-LAST:event_ExcluirUsuariobtnActionPerformed

    private void PesquisaUsuariotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PesquisaUsuariotxtKeyReleased
        // TODO add your handling code here:
        
        String termoBusca = PesquisaUsuariotxt.getText().toLowerCase().trim();
        
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tableUsuariosCadastrados.getModel();
        modelo.setRowCount(0);
        
        
        Controller.UsuarioController controller = new Controller.UsuarioController();
        java.util.ArrayList<Model.Usuario> listaUsuarios = controller.listar();
        
        
        for (Model.Usuario usuario : listaUsuarios) {
            
            if (termoBusca.isEmpty() || usuario.getNome().toLowerCase().contains(termoBusca)) {
                Object[] linha = new Object[]{
                    usuario.getNome(),
                    usuario.getCpf(),
                    usuario.getPerfil()
                };
                modelo.addRow(linha); 
            }
        }
    }//GEN-LAST:event_PesquisaUsuariotxtKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarEditarUsuariobtn;
    private javax.swing.JButton ExcluirUsuariobtn;
    private javax.swing.JTextField PesquisaUsuariotxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableUsuariosCadastrados;
    // End of variables declaration//GEN-END:variables
}
