/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelExpedicao;
import Controller.ClienteController;
import Controller.UsuarioController;
import Controller.ProdutosController;
import Model.Cliente;
import Model.Usuario;
import Model.Produtos;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author devdouglas
 */
public class CadastrarPedido extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarPedido
     */
    public CadastrarPedido() {
        initComponents();
        carregarClientes();   
        carregarMotoristas(); 
        carregarProdutos();  
    }
    
     
    private void carregarClientes() {
        ClienteController clienteController = new ClienteController();
        ArrayList<Cliente> listaClientes = clienteController.listar();
        
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        modeloCombo.addElement("Selecione um Cliente...");
        
        for (Cliente cliente : listaClientes) {
            modeloCombo.addElement(cliente.getNomeEmpresa());
        }
        cbSelecionaCliente.setModel(modeloCombo);
    }

    
    private void carregarMotoristas() {
        UsuarioController usuarioController = new UsuarioController();
        ArrayList<Usuario> listaUsuarios = usuarioController.listar();
        
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        modeloCombo.addElement("Selecione um Motorista...");
        
        for (Usuario usuario : listaUsuarios) {
            
            if ("Motorista".equalsIgnoreCase(usuario.getPerfil())) {
                modeloCombo.addElement(usuario.getNome());
            }
        }
        cbSelecionaMotorista.setModel(modeloCombo);
    }

  
    private void carregarProdutos() {
        ProdutosController produtosController = new ProdutosController();
        ArrayList<Produtos> listaProdutos = produtosController.listar();
        
        DefaultComboBoxModel<String> modeloCombo = new DefaultComboBoxModel<>();
        modeloCombo.addElement("Selecione um Produto...");
        
        for (Produtos produto : listaProdutos) {
            modeloCombo.addElement(produto.getNomeProduto());
        }
        cbSelecionaProduto.setModel(modeloCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbSelecionaCliente = new javax.swing.JComboBox<>();
        cbSelecionaProduto = new javax.swing.JComboBox<>();
        txtQuantidadeProdutosPedidos = new javax.swing.JTextField();
        cbSelecionaMotorista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutosPedidosAdc = new javax.swing.JTable();
        btnAdicionaProdutoPedido = new javax.swing.JButton();
        btnExcluiProdutoPedido = new javax.swing.JButton();
        btnSalvarPedido = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setForeground(new java.awt.Color(255, 255, 255));
        setFocusCycleRoot(true);
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));
        setPreferredSize(new java.awt.Dimension(804, 657));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE EXPEDIÇÃO");

        jLabel2.setText("SELECIONE O CLIENTE:");

        jLabel3.setText("SELECIONE O PRODUTO:");

        jLabel4.setText("QUANTIDADE:");

        jLabel5.setText("SELECIONE O MOTORISTA:");

        cbSelecionaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        cbSelecionaMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        tableProdutosPedidosAdc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Quantidade", "Produto", "Unidade"
            }
        ));
        jScrollPane1.setViewportView(tableProdutosPedidosAdc);

        btnAdicionaProdutoPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnAdicionaProdutoPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionaProdutoPedido.setText("ADICIONAR PRODUTO");
        btnAdicionaProdutoPedido.addActionListener(this::btnAdicionaProdutoPedidoActionPerformed);

        btnExcluiProdutoPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnExcluiProdutoPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluiProdutoPedido.setText("EXCLUIR PRODUTO");
        btnExcluiProdutoPedido.addActionListener(this::btnExcluiProdutoPedidoActionPerformed);

        btnSalvarPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarPedido.setText("SALVAR");
        btnSalvarPedido.addActionListener(this::btnSalvarPedidoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(txtQuantidadeProdutosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSelecionaCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSelecionaProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbSelecionaMotorista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdicionaProdutoPedido)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluiProdutoPedido))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGap(64, 64, 64))
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnSalvarPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(188, 188, 188))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cbSelecionaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbSelecionaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnAdicionaProdutoPedido)
                    .addComponent(btnExcluiProdutoPedido))
                .addGap(18, 18, 18)
                .addComponent(txtQuantidadeProdutosPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(cbSelecionaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarPedido)
                    .addComponent(btnCancelar))
                .addContainerGap(78, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluiProdutoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiProdutoPedidoActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tableProdutosPedidosAdc.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um produto da lista lateral para remover.");
            return;
        }
        
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) tableProdutosPedidosAdc.getModel();
        modeloTabela.removeRow(linhaSelecionada);
    }//GEN-LAST:event_btnExcluiProdutoPedidoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelExpedicao.GerenciamentoExpedicao());
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarPedidoActionPerformed
        // TODO add your handling code here:
        
        if (cbSelecionaCliente.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente para o pedido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (cbSelecionaMotorista.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, atribua um motorista para esta expedição!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

       
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) tableProdutosPedidosAdc.getModel();
        int totalLinhas = modeloTabela.getRowCount();
        
        if (totalLinhas == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, adicione pelo menos um produto ao pedido antes de salvar!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        Model.Expedicao novoPedido = new Model.Expedicao();
        novoPedido.setCliente(cbSelecionaCliente.getSelectedItem().toString());
        novoPedido.setMotorista(cbSelecionaMotorista.getSelectedItem().toString());
        novoPedido.setStatus("Aguardando"); // Atribuição automática exigida por padrão

       
        for (int i = 0; i < totalLinhas; i++) {
          
            int qtd = (int) modeloTabela.getValueAt(i, 0);
            String nomeProd = modeloTabela.getValueAt(i, 1).toString();
            String unidade = modeloTabela.getValueAt(i, 2).toString();
            
          
            Model.Produtos item = new Model.Produtos();
            item.setQuantidade(qtd);
            item.setNomeProduto(nomeProd);
            item.setUnidade(unidade);
            
            
            novoPedido.adicionarItem(item);
        }

        
        Controller.ExpedicaoController controller = new Controller.ExpedicaoController();
        controller.salvar(novoPedido);

       
        javax.swing.JOptionPane.showMessageDialog(this, "Pedido de expedição registrado com sucesso!");

        
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new PanelExpedicao.GerenciamentoExpedicao());
        
    }//GEN-LAST:event_btnSalvarPedidoActionPerformed

    private void btnAdicionaProdutoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaProdutoPedidoActionPerformed
        // TODO add your handling code here:
          // 1. VALIDAÇÃO DO COMBOBOX DE PRODUTO
        if (cbSelecionaProduto.getSelectedIndex() <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um produto válido!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 2. VALIDAÇÃO DO CAMPO DE QUANTIDADE
        if (txtQuantidadeProdutosPedidos.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, informe a quantidade do produto!", "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 3. TENTATIVA DE CONVERSÃO DA QUANTIDADE PARA NÚMERO
        int qtdInformada = 0;
        try {
            qtdInformada = Integer.parseInt(txtQuantidadeProdutosPedidos.getText().trim());
            if (qtdInformada <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "A quantidade deve ser maior que zero!", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira apenas números inteiros no campo QUANTIDADE!", "Erro de Digitação", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 4. DESCOBRIR A UNIDADE DO PRODUTO (Buscando no controlador de produtos)
        String produtoNome = cbSelecionaProduto.getSelectedItem().toString();
        String unidadeMedida = "UN"; // Valor padrão caso não encontre
        
        Controller.ProdutosController produtosController = new Controller.ProdutosController();
        for (Model.Produtos p : produtosController.listar()) {
            if (p.getNomeProduto().equalsIgnoreCase(produtoNome)) {
                unidadeMedida = p.getUnidade(); // Captura a unidade real cadastrada (KG, CX, UN...)
                break;
            }
        }

        // 5. INSERIR A LINHA DENTRO DA JTABLE DA TELA
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) tableProdutosPedidosAdc.getModel();
        
        Object[] novaLinha = new Object[]{
            qtdInformada,   // Coluna 1: Quantidade
            produtoNome,    // Coluna 2: Produto
            unidadeMedida   // Coluna 3: Unidade
        };
        
        modeloTabela.addRow(novaLinha);

        // 6. LIMPAR E PREPARAR O CAMPO PARA O PRÓXIMO PRODUTO
        txtQuantidadeProdutosPedidos.setText("");
        cbSelecionaProduto.setSelectedIndex(0);
    }//GEN-LAST:event_btnAdicionaProdutoPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionaProdutoPedido;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluiProdutoPedido;
    private javax.swing.JButton btnSalvarPedido;
    private javax.swing.JComboBox<String> cbSelecionaCliente;
    private javax.swing.JComboBox<String> cbSelecionaMotorista;
    private javax.swing.JComboBox<String> cbSelecionaProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutosPedidosAdc;
    private javax.swing.JTextField txtQuantidadeProdutosPedidos;
    // End of variables declaration//GEN-END:variables
}
