/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelExpedicao;
import javax.swing.table.DefaultTableModel;
import Controller.ExpedicaoController;
import Model.Expedicao;
import Model.Produtos;
import java.util.ArrayList;


/**
 *
 * @author devdouglas
 */
public class GerenciamentoExpedicao extends javax.swing.JPanel {

    /**
     * Creates new form GerenciamentoExpedicao
     */
    public GerenciamentoExpedicao() {
        initComponents();
        tablePedidos.setRowSelectionAllowed(true); 
        cbFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aguardando", "Em Separação", "Separado" }));
        atualizarTabela();
    }
    
    public final void atualizarTabela() {
        DefaultTableModel modelo = (DefaultTableModel) tablePedidos.getModel();
        modelo.setRowCount(0); // Limpa rascunhos visuais
        
        ExpedicaoController controller = new ExpedicaoController();
        ArrayList<Expedicao> lista = controller.listar();
        
        // Vincula o renderizador personalizado à coluna de índice 4 (Coluna "Status")
        tablePedidos.getColumnModel().getColumn(4).setCellRenderer(new StatusCellRenderer());
        
        // Contador para simular o número sequencial do Pedido
        int numeroPedido = 1; 
        
        for (Expedicao exp : lista) {
            // Unifica os nomes dos produtos e soma a quantidade total do pedido
            StringBuilder nomesProdutos = new StringBuilder();
            int qtdTotal = 0;
            
            for (Produtos p : exp.getItensPedido()) {
                if (nomesProdutos.length() > 0) nomesProdutos.append(", ");
                nomesProdutos.append(p.getNomeProduto());
                qtdTotal += p.getQuantidade();
            }
            
            Object[] linha = new Object[]{
                "#" + numeroPedido++,     // Pedido
                exp.getCliente(),         // Cliente
                nomesProdutos.toString(), // Produtos unificados
                qtdTotal,                 // Quantidade total calculada
                exp.getStatus(),          // Status (Será interceptado e pintado de azul)
                exp.getMotorista()        // Motorista
            };
            modelo.addRow(linha);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbFiltroStatus = new javax.swing.JComboBox<>();
        btnCriarEditarPedidos = new javax.swing.JButton();
        btnVisualizarPedido = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE EXPEDIÇÃO");

        tablePedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pedido", "Cliente", "Produtos", "Quantidade", "Status", "Motorista"
            }
        ));
        jScrollPane1.setViewportView(tablePedidos);

        jLabel2.setText("Filtrar pelo status:");

        cbFiltroStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnCriarEditarPedidos.setBackground(new java.awt.Color(0, 0, 0));
        btnCriarEditarPedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnCriarEditarPedidos.setText("CRIAR/EDITAR PEDIDO");
        btnCriarEditarPedidos.addActionListener(this::btnCriarEditarPedidosActionPerformed);

        btnVisualizarPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnVisualizarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnVisualizarPedido.setText("VISUALIZAR PEDIDO");
        btnVisualizarPedido.addActionListener(this::btnVisualizarPedidoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVisualizarPedido)
                        .addGap(132, 132, 132)
                        .addComponent(btnCriarEditarPedidos)
                        .addGap(139, 139, 139))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbFiltroStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarPedido)
                    .addComponent(btnCriarEditarPedidos))
                .addContainerGap(258, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarEditarPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarEditarPedidosActionPerformed
        // TODO add your handling code here:
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new CadastrarPedido());
       
    }//GEN-LAST:event_btnCriarEditarPedidosActionPerformed

    private void btnVisualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarPedidoActionPerformed
        // TODO add your handling code here:
        
        int linhaSelecionada = tablePedidos.getSelectedRow();
        
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique primeiro em um pedido na tabela e depois em VISUALIZAR PEDIDO!");
            return;
        }
        
       
        Controller.ExpedicaoController controller = new Controller.ExpedicaoController();
        Model.Expedicao pedidoSelecionado = controller.listar().get(linhaSelecionada);
        int numeroDoPedido = linhaSelecionada + 1;
        
       
        Telas.Dashboard dashboard = (Telas.Dashboard) javax.swing.SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new VisualizarPedidos(pedidoSelecionado, numeroDoPedido));
    }//GEN-LAST:event_btnVisualizarPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarEditarPedidos;
    private javax.swing.JButton btnVisualizarPedido;
    private javax.swing.JComboBox<String> cbFiltroStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePedidos;
    // End of variables declaration//GEN-END:variables
}
