/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PanelExpedicao;

import Model.Expedicao;
import Model.Produtos;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import Telas.Dashboard;
import javax.swing.SwingUtilities;
/**
 *
 * @author devdouglas
 */
public class VisualizarPedidos extends javax.swing.JPanel {
    private Expedicao pedidoAtual = null;
    /**
     * Creates new form VisualizarPedidos
     */
    public VisualizarPedidos() {
        initComponents();
        configurarOpcoesStatus();
    }
    
    public VisualizarPedidos(Expedicao pedido, int numeroPedidoExibicao) {
        initComponents();
        this.pedidoAtual = pedido;
        
        // 1. Configura os status disponíveis no ComboBox
        configurarOpcoesStatus();
        cbAtualizaStatus.setSelectedItem(pedido.getStatus());
        
        // 2. Preenche a tabela interna com os itens do pedido
        DefaultTableModel modelo = (DefaultTableModel) tableVisualizadorPedidos.getModel();
        modelo.setRowCount(0);
        
        for (Produtos p : pedido.getItensPedido()) {
            Object[] linha = new Object[]{
                "#" + numeroPedidoExibicao, // Número do Pedido
                pedido.getCliente(),         // Cliente
                p.getNomeProduto(),         // Produto individual
                p.getQuantidade()           // Quantidade individual
            };
            modelo.addRow(linha);
        }
    }

    private void configurarOpcoesStatus() {
        cbAtualizaStatus.setModel(new DefaultComboBoxModel<>(new String[] {
            "Aguardando", "Em Separação", "Separado"
        }));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVisualizadorPedidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cbAtualizaStatus = new javax.swing.JComboBox<>();
        btnSalvarSeparacaoPedido = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 153));
        setMaximumSize(new java.awt.Dimension(804, 657));
        setMinimumSize(new java.awt.Dimension(804, 657));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setText("GERENCIAMENTO DE EXPEDIÇÃO");

        tableVisualizadorPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pedido", "Cliente", "Produtos", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(tableVisualizadorPedidos);

        jLabel2.setText("Atualizar Status:");

        btnSalvarSeparacaoPedido.setBackground(new java.awt.Color(0, 0, 0));
        btnSalvarSeparacaoPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarSeparacaoPedido.setText("SALVAR");
        btnSalvarSeparacaoPedido.addActionListener(this::btnSalvarSeparacaoPedidoActionPerformed);

        btnCancelar.setBackground(new java.awt.Color(0, 0, 0));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAtualizaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnSalvarSeparacaoPedido)
                        .addGap(146, 146, 146)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAtualizaStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarSeparacaoPedido)
                    .addComponent(btnCancelar))
                .addContainerGap(227, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarSeparacaoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarSeparacaoPedidoActionPerformed
        // TODO add your handling code here:
        if (this.pedidoAtual != null) {
            // Atualiza o status do objeto direto na memória ram
            String novoStatus = cbAtualizaStatus.getSelectedItem().toString();
            this.pedidoAtual.setStatus(novoStatus);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Status do pedido atualizado para: " + novoStatus);
        }
        
      
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new GerenciamentoExpedicao());
    }//GEN-LAST:event_btnSalvarSeparacaoPedidoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        Dashboard dashboard = (Dashboard) SwingUtilities.getWindowAncestor(this);
        dashboard.abrirPainel(new GerenciamentoExpedicao());
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvarSeparacaoPedido;
    private javax.swing.JComboBox<String> cbAtualizaStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVisualizadorPedidos;
    // End of variables declaration//GEN-END:variables
}
